Falak/feedback Closes #17
acm-ucr/R-Mate pull request #26
Opened 2023-04-21 04:09 UTC by Tech13-08

![image](https://user-images.githubusercontent.com/68032044/233538904-b03c9907-8c28-4424-9927-d9faf9fa7272.png)

2023-04-21 04:11 UTC, Tech13-08 commented
Closes #17

2023-04-21 05:58 UTC, MenthyWu requested changes
Can you change styleSheet to tailwind 😭

2023-04-21 06:01 UTC, menthy-wu requested changes
Can you change styleSheet to tailwind 😭 (I use the wrong account lol)

2023-04-23 21:56 UTC, menthy-wu approved these changes

2023-04-23 21:57 UTC, merged